version: "3.3"
services:
  #------------------------------------------------------------------------
  business-area-service:
    build: ./business-area-service/
    image: edu/business-area-service
    container_name: business-area-service
    ports:
      - 8180:8180
      - 5105:5105
    environment:
#      DB_HOST: business-area-service-postgres
      CONFIG_SERVER_HOST: config-server
    depends_on:
      - business-area-service-postgres
      - config-server
      - rabbitmq
    networks:
      pm-network:
        ipv4_address: 172.22.0.4

  business-area-service-postgres:
    image: postgres
    container_name: business-area-service-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: business1
      POSTGRES_PASSWORD: business1
      POSTGRES_DB: business1
    networks:
      pm-network:
        ipv4_address: 172.22.0.5
  #------------------------------------------------------------------------
  product-service:
    build: ./product-service/
    image: edu/product-service
    container_name: product-service
    ports:
      - 8280:8280
      - 5205:5205
    environment:
#      DB_HOST: product-service-postgres
      CONFIG_SERVER_HOST: config-server
    depends_on:
      - product-service-postgres
      - config-server
      - rabbitmq
    networks:
      pm-network:
        ipv4_address: 172.22.0.8

  product-service-postgres:
    image: postgres
    container_name: product-service-postgres
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: product1
      POSTGRES_PASSWORD: product1
      POSTGRES_DB: product1
    networks:
      pm-network:
        ipv4_address: 172.22.0.9
  #------------------------------------------------------------------------
  client-service:
    build: ./client-service/
    image: edu/client-service
    container_name: client-service
    ports:
      - 8380:8380
      - 5305:5305
    environment:
#      DB_HOST: client-service-postgres
      CONFIG_SERVER_HOST: config-server
    depends_on:
      - client-service-postgres
      - config-server
      - rabbitmq
    networks:
      pm-network:
        ipv4_address: 172.22.0.6

  client-service-postgres:
    image: postgres
    container_name: client-service-postgres
    ports:
      - 5452:5432
    environment:
      POSTGRES_USER: client1
      POSTGRES_PASSWORD: client1
      POSTGRES_DB: client1
    networks:
      pm-network:
        ipv4_address: 172.22.0.7
  #------------------------------------------------------------------------
  research-project-service:
    build: ./research-project/
    image: edu/research-project-service
    container_name: research-project-service
    ports:
      - 8480:8480
      - 5405:5405
    environment:
#      DB_HOST: research-project-service-postgres
      CONFIG_SERVER_HOST: config-server
    depends_on:
      - research-project-service-postgres
      - config-server
      - rabbitmq
    networks:
      pm-network:
        ipv4_address: 172.22.0.10

  research-project-service-postgres:
    image: postgres
    container_name: research-project-service-postgres
    ports:
      - 5462:5432
    environment:
      POSTGRES_USER: research1
      POSTGRES_PASSWORD: research1
      POSTGRES_DB: research1
    networks:
      pm-network:
        ipv4_address: 172.22.0.11
  #------------------------------------------------------------------------
  resources-service:
    build: ./resources-service/
    image: edu/resources-service
    container_name: resources-service
    ports:
      - 8580:8580
      - 5505:5505
    environment:
#      DB_HOST: resources-service-postgres
      CONFIG_SERVER_HOST: config-server
    depends_on:
      - resources-service-postgres
      - config-server
      - rabbitmq
    networks:
      pm-network:
        ipv4_address: 172.22.0.12

  resources-service-postgres:
    image: postgres
    container_name: resources-service-postgres
    ports:
      - 5472:5432
    environment:
      POSTGRES_USER: resources1
      POSTGRES_PASSWORD: resources1
      POSTGRES_DB: resources1
    networks:
      pm-network:
        ipv4_address: 172.22.0.13


  config-server:
    build: ./config-server/
    image: edu/config-server
    container_name: config-server
    ports:
      - 8888:8888
    volumes:
      - ./config-repo:/config
    networks:
      pm-network:
        ipv4_address: 172.22.0.2

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pm-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      pm-network:
        ipv4_address: 172.22.0.3

networks:
  pm-network:
    external: true
