server:
  port: 8280

app:
  rabbit:
    exchange_name: ${RABBITMQ_EXCHANGE:fanout.exchange}
    active_queue: ${RABBITMQ_QUEUE:event_queue2}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:product1}
    username: ${DB_USERNAME:product1}
    password: ${DB_PASSWORD:product1}
  jpa:
    generate-ddl: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info,health,env,refresh
  endpoint:
    health:
      show-details: always
      